config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'landing#index'

  resources :countries, only: :show, param: :country_code
  resources :currencies, only: [:index, :show]
  resources :countries_users_relations, only: :create do
    delete ':country_id', to: 'countries_users_relations#destroy', on: :collection
  end
  resources :trips, only: [:new, :create, :index]
end

app/models/countries_users_relation.rb
class CountriesUsersRelation < ActiveRecord::Base
  belongs_to :user
  belongs_to :country

  validates :user_id, presence: true
  validates :country_id, presence: true, uniqueness: { scope: :user_id }
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :code, presence: true, uniqueness: true, length: { maximum: 2 }
  validates :name, presence: true

  belongs_to :currency
  has_many :countries_users_relations
  has_many :users, through: :countries_users_relations
  has_and_belongs_to_many :trips

  scope :by_code, -> (code) { find_by(code: code) }
  scope :with_currency, -> { includes(:currency) }

  def self.not_visited(user_id)
    where.not(id: CountriesUsersRelation.select(:country_id).where(user_id: user_id))

    # RAW SQL
    # Country.find_by_sql("SELECT * FROM countries
    # LEFT JOIN countries_users_relations cur ON countries.id = cur.country_id AND cur.user_id = (?)
    # WHERE cur.id IS NULL", user_id)
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  validates :code, length: { maximum: 3 }

  has_many :countries

  scope :by_name, -> { order(:name) }
  scope :countries_users_reference, -> { references(:countries_users_relations) }

  def self.with_countries_and_visits(user_id)
    includes(countries: :countries_users_relations)
      .where('countries_users_relations.user_id = (?) OR
              countries_users_relations.user_id IS NULL', user_id)
  end

  def not_visited_countries_size
    visited_count = countries.to_a.count do |country|
      country.countries_users_relations.any?
    end
    countries.size - visited_count
  end

  def self.without_visited(user_id)
    includes(countries: :countries_users_relations)
    .where(id: Country.not_visited(user_id).select('countries.currency_id'))
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :countries

  validates :start_date, presence: true
  validates :end_date,   presence: true

  def mark_visited_countries
    return if end_date >= Date.today
    countries.each do |country|
      CountriesUsersRelation.create(country: country, user: user)
    end
    update(finished: true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :countries_users_relations
  has_many :visited_countries, through: :countries_users_relations, source: :country
  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def show
    country = Country.with_currency.by_code(params[:country_code])
    render json: country, include: :currency
  end
end

app/controllers/countries_users_relations_controller.rb
class CountriesUsersRelationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_up_relation
  respond_to :json

  def create
    render nothing: true, status: @relation.save ? 200 : 422
  end

  def destroy
    if @relation
      @relation.destroy
      render nothing: true, status: 204
    else
      render nothing: true, status: 410
    end
  end

  private

  def set_up_relation
    @relation = CountriesUsersRelation.where(user: current_user,
      country_id: params[:country_id]).first_or_initialize
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    if user_signed_in?
      @hide_visited = params[:hide_visited]
      @currencies = CurrenciesManager.new(params, current_user).list_for_user
    else
      @currencies = Currency.includes(:countries).by_name
    end
  end

  def show
    @currency = if user_signed_in?
      CurrenciesManager.new(params, current_user).show_for_user
    else
      Currency.includes(:countries).find(params[:id])
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!

  def index
    @trips = Trip.includes(:countries).order(end_date: :desc)
  end

  def new
    @countries = Country.all
  end

  def create
    trip = Trip.new(create_trip_params.merge(user: current_user))
    if trip.save
      trip.mark_visited_countries
      render nothing: true, status: 200
    else
      render nothing: true, status: 422
    end
  end

  private

  def create_trip_params
    params.require(:trip).permit(:start_date, :end_date, :description, country_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/currencies/index.html.haml
- if user_signed_in?
  - if @hide_visited
    = link_to 'Show visited countries', currencies_path
  - else
    = link_to 'Hide visited countries', currencies_path(hide_visited: true)

%ol
  - @currencies.each do |currency|
    %li
      %p
        Currency name:
        = link_to currency.name, currency_path(currency)
      %p
        Currency code:
        %span
          = currency.code
      %p
        Countries for this currency:
        %span
          = link_to currency.countries.size, currency_path(currency)
      - if user_signed_in?
        %p
          Not visited countries:
          %span
            = currency.not_visited_countries_size

app/views/currencies/show.html.haml
%h4
  Currency name:
  %span
    = @currency.name

Countries for this currency:
%ul
  - @currency.countries.each do |country|
    %li
      %p
        Country name:
        %span
          = country.name
      %p
        Country code:
        %span
          = country.code
      - if user_signed_in?
        = check_box_tag "visited-country", country.id, !country.countries_users_relations.empty?, class: 'visited-mark'
        I've been there

app/views/landing/index.html.haml
%p= link_to 'List of available currencies', currencies_path
- if user_signed_in?
  %p= link_to 'Create a trip', new_trip_path
  %p= link_to 'Trips list', trips_path

%input#country(type="text" readonly)
%input#country_code(type="hidden")
%p
  Country name:
  %span#country-name
%p
  Country code:
  %span#country-code
%p
  Country currency:
  %span#country-currency
%p
  Country currency code:
  %span#country-currency-code

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title SoapService
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
%body
  - if user_signed_in?
    = link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    = link_to 'Sign in', new_user_session_path
    = link_to 'Sign up', new_user_registration_path
  = link_to 'Home', root_path
  %p.notice
    = notice
  %p.alert
    = alert

= yield

app/views/trips/index.html.haml
- if @trips.any?
  %h4 Made trips
- else
  %h4 You have no trips yet
  = link_to 'Create a trip', new_trip_path

%ol
- @trips.each do |trip|
  %li
    %p
      Number of visited countries:
      %span
        = trip.countries.size
    %p
      Start date:
      %span
        = trip.start_date
    %p
      End date:
      %span
        = trip.end_date
    %p
      Description:
      %p
        = trip.description
  %hr

app/views/trips/new.html.haml
%textarea#description(placeholder="Describe your trip")
%br
Start date:
%input#start-date(type="date" placeholder="Start date of your trip")
%br
End date:
%input#end-date(type="date" placeholder="End date of your trip")
%p
Select vsited countries:
%br
= select_tag 'countries', options_from_collection_for_select(@countries, "id", "name"), multiple: true, style: 'height:300px'
= button_tag "Create trip", id: 'save-trip'